name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_SECRET: ${{ secrets.APP.SECRET}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build step (unsafe)
        run: bash scripts/build.sh

      - name: Upload build artifact (untrusted)
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: app.py

      - name: Download build artifact (no integrity check)
        uses: actions/download-artifact@v3
        with:
          name: app-build

      - name: Deploy to production (no approval)
        run: bash scripts/deploy.sh
